/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PillarsRouteImport } from './routes/pillars'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as OriginsRouteImport } from './routes/origins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultConsultIdRouteImport } from './routes/consult_.$consultId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedOwnerManualRouteImport } from './routes/_authenticated/owner-manual'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedExpertRouteImport } from './routes/_authenticated/_expert'
import { Route as ConsultConsultIdIndexRouteImport } from './routes/consult_.$consultId.index'
import { Route as ConsultConsultIdResultRouteImport } from './routes/consult_.$consultId.result'
import { Route as AuthenticatedExpertExpertRouteImport } from './routes/_authenticated/_expert/expert'
import { Route as AuthenticatedExpertExpertPrescriptionIdRouteImport } from './routes/_authenticated/_expert/expert_.$prescriptionId'
import { Route as AuthenticatedExpertExpertCatalogRouteImport } from './routes/_authenticated/_expert/expert.catalog'
import { Route as AuthenticatedExpertExpertConsultConsultIdRouteImport } from './routes/_authenticated/_expert/expert_.consult.$consultId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarsRoute = PillarsRouteImport.update({
  id: '/pillars',
  path: '/pillars',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginsRoute = OriginsRouteImport.update({
  id: '/origins',
  path: '/origins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultConsultIdRoute = ConsultConsultIdRouteImport.update({
  id: '/consult_/$consultId',
  path: '/consult/$consultId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerManualRoute =
  AuthenticatedOwnerManualRouteImport.update({
    id: '/owner-manual',
    path: '/owner-manual',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpertRoute = AuthenticatedExpertRouteImport.update({
  id: '/_expert',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ConsultConsultIdIndexRoute = ConsultConsultIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultConsultIdRoute,
} as any)
const ConsultConsultIdResultRoute = ConsultConsultIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => ConsultConsultIdRoute,
} as any)
const AuthenticatedExpertExpertRoute =
  AuthenticatedExpertExpertRouteImport.update({
    id: '/expert',
    path: '/expert',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)
const AuthenticatedExpertExpertPrescriptionIdRoute =
  AuthenticatedExpertExpertPrescriptionIdRouteImport.update({
    id: '/expert_/$prescriptionId',
    path: '/expert/$prescriptionId',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)
const AuthenticatedExpertExpertCatalogRoute =
  AuthenticatedExpertExpertCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedExpertExpertRoute,
  } as any)
const AuthenticatedExpertExpertConsultConsultIdRoute =
  AuthenticatedExpertExpertConsultConsultIdRouteImport.update({
    id: '/expert_/consult/$consultId',
    path: '/expert/consult/$consultId',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consult': typeof ConsultRoute
  '/integrity': typeof IntegrityRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/origins': typeof OriginsRoute
  '/philosophy': typeof PhilosophyRoute
  '/pillars': typeof PillarsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account': typeof AuthenticatedAccountRoute
  '/owner-manual': typeof AuthenticatedOwnerManualRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/consult/$consultId': typeof ConsultConsultIdRouteWithChildren
  '/expert': typeof AuthenticatedExpertExpertRouteWithChildren
  '/consult/$consultId/result': typeof ConsultConsultIdResultRoute
  '/consult/$consultId/': typeof ConsultConsultIdIndexRoute
  '/expert/catalog': typeof AuthenticatedExpertExpertCatalogRoute
  '/expert/$prescriptionId': typeof AuthenticatedExpertExpertPrescriptionIdRoute
  '/expert/consult/$consultId': typeof AuthenticatedExpertExpertConsultConsultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consult': typeof ConsultRoute
  '/integrity': typeof IntegrityRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/origins': typeof OriginsRoute
  '/philosophy': typeof PhilosophyRoute
  '/pillars': typeof PillarsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account': typeof AuthenticatedAccountRoute
  '/owner-manual': typeof AuthenticatedOwnerManualRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/expert': typeof AuthenticatedExpertExpertRouteWithChildren
  '/consult/$consultId/result': typeof ConsultConsultIdResultRoute
  '/consult/$consultId': typeof ConsultConsultIdIndexRoute
  '/expert/catalog': typeof AuthenticatedExpertExpertCatalogRoute
  '/expert/$prescriptionId': typeof AuthenticatedExpertExpertPrescriptionIdRoute
  '/expert/consult/$consultId': typeof AuthenticatedExpertExpertConsultConsultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/consult': typeof ConsultRoute
  '/integrity': typeof IntegrityRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/origins': typeof OriginsRoute
  '/philosophy': typeof PhilosophyRoute
  '/pillars': typeof PillarsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/_expert': typeof AuthenticatedExpertRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/owner-manual': typeof AuthenticatedOwnerManualRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/consult_/$consultId': typeof ConsultConsultIdRouteWithChildren
  '/_authenticated/_expert/expert': typeof AuthenticatedExpertExpertRouteWithChildren
  '/consult_/$consultId/result': typeof ConsultConsultIdResultRoute
  '/consult_/$consultId/': typeof ConsultConsultIdIndexRoute
  '/_authenticated/_expert/expert/catalog': typeof AuthenticatedExpertExpertCatalogRoute
  '/_authenticated/_expert/expert_/$prescriptionId': typeof AuthenticatedExpertExpertPrescriptionIdRoute
  '/_authenticated/_expert/expert_/consult/$consultId': typeof AuthenticatedExpertExpertConsultConsultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consult'
    | '/integrity'
    | '/journey'
    | '/login'
    | '/origins'
    | '/philosophy'
    | '/pillars'
    | '/reset-password'
    | '/signup'
    | '/unauthorized'
    | '/account'
    | '/owner-manual'
    | '/auth/callback'
    | '/consult/$consultId'
    | '/expert'
    | '/consult/$consultId/result'
    | '/consult/$consultId/'
    | '/expert/catalog'
    | '/expert/$prescriptionId'
    | '/expert/consult/$consultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consult'
    | '/integrity'
    | '/journey'
    | '/login'
    | '/origins'
    | '/philosophy'
    | '/pillars'
    | '/reset-password'
    | '/signup'
    | '/unauthorized'
    | '/account'
    | '/owner-manual'
    | '/auth/callback'
    | '/expert'
    | '/consult/$consultId/result'
    | '/consult/$consultId'
    | '/expert/catalog'
    | '/expert/$prescriptionId'
    | '/expert/consult/$consultId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/consult'
    | '/integrity'
    | '/journey'
    | '/login'
    | '/origins'
    | '/philosophy'
    | '/pillars'
    | '/reset-password'
    | '/signup'
    | '/unauthorized'
    | '/_authenticated/_expert'
    | '/_authenticated/account'
    | '/_authenticated/owner-manual'
    | '/auth/callback'
    | '/consult_/$consultId'
    | '/_authenticated/_expert/expert'
    | '/consult_/$consultId/result'
    | '/consult_/$consultId/'
    | '/_authenticated/_expert/expert/catalog'
    | '/_authenticated/_expert/expert_/$prescriptionId'
    | '/_authenticated/_expert/expert_/consult/$consultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConsultRoute: typeof ConsultRoute
  IntegrityRoute: typeof IntegrityRoute
  JourneyRoute: typeof JourneyRoute
  LoginRoute: typeof LoginRoute
  OriginsRoute: typeof OriginsRoute
  PhilosophyRoute: typeof PhilosophyRoute
  PillarsRoute: typeof PillarsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ConsultConsultIdRoute: typeof ConsultConsultIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillars': {
      id: '/pillars'
      path: '/pillars'
      fullPath: '/pillars'
      preLoaderRoute: typeof PillarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origins': {
      id: '/origins'
      path: '/origins'
      fullPath: '/origins'
      preLoaderRoute: typeof OriginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult_/$consultId': {
      id: '/consult_/$consultId'
      path: '/consult/$consultId'
      fullPath: '/consult/$consultId'
      preLoaderRoute: typeof ConsultConsultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner-manual': {
      id: '/_authenticated/owner-manual'
      path: '/owner-manual'
      fullPath: '/owner-manual'
      preLoaderRoute: typeof AuthenticatedOwnerManualRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_expert': {
      id: '/_authenticated/_expert'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedExpertRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/consult_/$consultId/': {
      id: '/consult_/$consultId/'
      path: '/'
      fullPath: '/consult/$consultId/'
      preLoaderRoute: typeof ConsultConsultIdIndexRouteImport
      parentRoute: typeof ConsultConsultIdRoute
    }
    '/consult_/$consultId/result': {
      id: '/consult_/$consultId/result'
      path: '/result'
      fullPath: '/consult/$consultId/result'
      preLoaderRoute: typeof ConsultConsultIdResultRouteImport
      parentRoute: typeof ConsultConsultIdRoute
    }
    '/_authenticated/_expert/expert': {
      id: '/_authenticated/_expert/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof AuthenticatedExpertExpertRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
    '/_authenticated/_expert/expert_/$prescriptionId': {
      id: '/_authenticated/_expert/expert_/$prescriptionId'
      path: '/expert/$prescriptionId'
      fullPath: '/expert/$prescriptionId'
      preLoaderRoute: typeof AuthenticatedExpertExpertPrescriptionIdRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
    '/_authenticated/_expert/expert/catalog': {
      id: '/_authenticated/_expert/expert/catalog'
      path: '/catalog'
      fullPath: '/expert/catalog'
      preLoaderRoute: typeof AuthenticatedExpertExpertCatalogRouteImport
      parentRoute: typeof AuthenticatedExpertExpertRoute
    }
    '/_authenticated/_expert/expert_/consult/$consultId': {
      id: '/_authenticated/_expert/expert_/consult/$consultId'
      path: '/expert/consult/$consultId'
      fullPath: '/expert/consult/$consultId'
      preLoaderRoute: typeof AuthenticatedExpertExpertConsultConsultIdRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
  }
}

interface AuthenticatedExpertExpertRouteChildren {
  AuthenticatedExpertExpertCatalogRoute: typeof AuthenticatedExpertExpertCatalogRoute
}

const AuthenticatedExpertExpertRouteChildren: AuthenticatedExpertExpertRouteChildren =
  {
    AuthenticatedExpertExpertCatalogRoute:
      AuthenticatedExpertExpertCatalogRoute,
  }

const AuthenticatedExpertExpertRouteWithChildren =
  AuthenticatedExpertExpertRoute._addFileChildren(
    AuthenticatedExpertExpertRouteChildren,
  )

interface AuthenticatedExpertRouteChildren {
  AuthenticatedExpertExpertRoute: typeof AuthenticatedExpertExpertRouteWithChildren
  AuthenticatedExpertExpertPrescriptionIdRoute: typeof AuthenticatedExpertExpertPrescriptionIdRoute
  AuthenticatedExpertExpertConsultConsultIdRoute: typeof AuthenticatedExpertExpertConsultConsultIdRoute
}

const AuthenticatedExpertRouteChildren: AuthenticatedExpertRouteChildren = {
  AuthenticatedExpertExpertRoute: AuthenticatedExpertExpertRouteWithChildren,
  AuthenticatedExpertExpertPrescriptionIdRoute:
    AuthenticatedExpertExpertPrescriptionIdRoute,
  AuthenticatedExpertExpertConsultConsultIdRoute:
    AuthenticatedExpertExpertConsultConsultIdRoute,
}

const AuthenticatedExpertRouteWithChildren =
  AuthenticatedExpertRoute._addFileChildren(AuthenticatedExpertRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedExpertRoute: typeof AuthenticatedExpertRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedOwnerManualRoute: typeof AuthenticatedOwnerManualRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedExpertRoute: AuthenticatedExpertRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedOwnerManualRoute: AuthenticatedOwnerManualRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ConsultConsultIdRouteChildren {
  ConsultConsultIdResultRoute: typeof ConsultConsultIdResultRoute
  ConsultConsultIdIndexRoute: typeof ConsultConsultIdIndexRoute
}

const ConsultConsultIdRouteChildren: ConsultConsultIdRouteChildren = {
  ConsultConsultIdResultRoute: ConsultConsultIdResultRoute,
  ConsultConsultIdIndexRoute: ConsultConsultIdIndexRoute,
}

const ConsultConsultIdRouteWithChildren =
  ConsultConsultIdRoute._addFileChildren(ConsultConsultIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConsultRoute: ConsultRoute,
  IntegrityRoute: IntegrityRoute,
  JourneyRoute: JourneyRoute,
  LoginRoute: LoginRoute,
  OriginsRoute: OriginsRoute,
  PhilosophyRoute: PhilosophyRoute,
  PillarsRoute: PillarsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ConsultConsultIdRoute: ConsultConsultIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
