/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PillarsRouteImport } from './routes/pillars'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as OriginsRouteImport } from './routes/origins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultConsultIdRouteImport } from './routes/consult.$consultId'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedExpertRouteImport } from './routes/_authenticated/_expert'
import { Route as ConsultConsultIdResultRouteImport } from './routes/consult.$consultId.result'
import { Route as AuthenticatedExpertExpertRouteImport } from './routes/_authenticated/_expert/expert'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarsRoute = PillarsRouteImport.update({
  id: '/pillars',
  path: '/pillars',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginsRoute = OriginsRouteImport.update({
  id: '/origins',
  path: '/origins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultConsultIdRoute = ConsultConsultIdRouteImport.update({
  id: '/$consultId',
  path: '/$consultId',
  getParentRoute: () => ConsultRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpertRoute = AuthenticatedExpertRouteImport.update({
  id: '/_expert',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ConsultConsultIdResultRoute = ConsultConsultIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => ConsultConsultIdRoute,
} as any)
const AuthenticatedExpertExpertRoute =
  AuthenticatedExpertExpertRouteImport.update({
    id: '/expert',
    path: '/expert',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consult': typeof ConsultRouteWithChildren
  '/integrity': typeof IntegrityRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/origins': typeof OriginsRoute
  '/philosophy': typeof PhilosophyRoute
  '/pillars': typeof PillarsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account': typeof AuthenticatedAccountRoute
  '/consult/$consultId': typeof ConsultConsultIdRouteWithChildren
  '/expert': typeof AuthenticatedExpertExpertRoute
  '/consult/$consultId/result': typeof ConsultConsultIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consult': typeof ConsultRouteWithChildren
  '/integrity': typeof IntegrityRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/origins': typeof OriginsRoute
  '/philosophy': typeof PhilosophyRoute
  '/pillars': typeof PillarsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account': typeof AuthenticatedAccountRoute
  '/consult/$consultId': typeof ConsultConsultIdRouteWithChildren
  '/expert': typeof AuthenticatedExpertExpertRoute
  '/consult/$consultId/result': typeof ConsultConsultIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/consult': typeof ConsultRouteWithChildren
  '/integrity': typeof IntegrityRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/origins': typeof OriginsRoute
  '/philosophy': typeof PhilosophyRoute
  '/pillars': typeof PillarsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/_expert': typeof AuthenticatedExpertRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/consult/$consultId': typeof ConsultConsultIdRouteWithChildren
  '/_authenticated/_expert/expert': typeof AuthenticatedExpertExpertRoute
  '/consult/$consultId/result': typeof ConsultConsultIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consult'
    | '/integrity'
    | '/journey'
    | '/login'
    | '/origins'
    | '/philosophy'
    | '/pillars'
    | '/reset-password'
    | '/signup'
    | '/unauthorized'
    | '/account'
    | '/consult/$consultId'
    | '/expert'
    | '/consult/$consultId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consult'
    | '/integrity'
    | '/journey'
    | '/login'
    | '/origins'
    | '/philosophy'
    | '/pillars'
    | '/reset-password'
    | '/signup'
    | '/unauthorized'
    | '/account'
    | '/consult/$consultId'
    | '/expert'
    | '/consult/$consultId/result'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/consult'
    | '/integrity'
    | '/journey'
    | '/login'
    | '/origins'
    | '/philosophy'
    | '/pillars'
    | '/reset-password'
    | '/signup'
    | '/unauthorized'
    | '/_authenticated/_expert'
    | '/_authenticated/account'
    | '/consult/$consultId'
    | '/_authenticated/_expert/expert'
    | '/consult/$consultId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConsultRoute: typeof ConsultRouteWithChildren
  IntegrityRoute: typeof IntegrityRoute
  JourneyRoute: typeof JourneyRoute
  LoginRoute: typeof LoginRoute
  OriginsRoute: typeof OriginsRoute
  PhilosophyRoute: typeof PhilosophyRoute
  PillarsRoute: typeof PillarsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillars': {
      id: '/pillars'
      path: '/pillars'
      fullPath: '/pillars'
      preLoaderRoute: typeof PillarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origins': {
      id: '/origins'
      path: '/origins'
      fullPath: '/origins'
      preLoaderRoute: typeof OriginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult/$consultId': {
      id: '/consult/$consultId'
      path: '/$consultId'
      fullPath: '/consult/$consultId'
      preLoaderRoute: typeof ConsultConsultIdRouteImport
      parentRoute: typeof ConsultRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_expert': {
      id: '/_authenticated/_expert'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedExpertRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/consult/$consultId/result': {
      id: '/consult/$consultId/result'
      path: '/result'
      fullPath: '/consult/$consultId/result'
      preLoaderRoute: typeof ConsultConsultIdResultRouteImport
      parentRoute: typeof ConsultConsultIdRoute
    }
    '/_authenticated/_expert/expert': {
      id: '/_authenticated/_expert/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof AuthenticatedExpertExpertRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
  }
}

interface AuthenticatedExpertRouteChildren {
  AuthenticatedExpertExpertRoute: typeof AuthenticatedExpertExpertRoute
}

const AuthenticatedExpertRouteChildren: AuthenticatedExpertRouteChildren = {
  AuthenticatedExpertExpertRoute: AuthenticatedExpertExpertRoute,
}

const AuthenticatedExpertRouteWithChildren =
  AuthenticatedExpertRoute._addFileChildren(AuthenticatedExpertRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedExpertRoute: typeof AuthenticatedExpertRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedExpertRoute: AuthenticatedExpertRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ConsultConsultIdRouteChildren {
  ConsultConsultIdResultRoute: typeof ConsultConsultIdResultRoute
}

const ConsultConsultIdRouteChildren: ConsultConsultIdRouteChildren = {
  ConsultConsultIdResultRoute: ConsultConsultIdResultRoute,
}

const ConsultConsultIdRouteWithChildren =
  ConsultConsultIdRoute._addFileChildren(ConsultConsultIdRouteChildren)

interface ConsultRouteChildren {
  ConsultConsultIdRoute: typeof ConsultConsultIdRouteWithChildren
}

const ConsultRouteChildren: ConsultRouteChildren = {
  ConsultConsultIdRoute: ConsultConsultIdRouteWithChildren,
}

const ConsultRouteWithChildren =
  ConsultRoute._addFileChildren(ConsultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConsultRoute: ConsultRouteWithChildren,
  IntegrityRoute: IntegrityRoute,
  JourneyRoute: JourneyRoute,
  LoginRoute: LoginRoute,
  OriginsRoute: OriginsRoute,
  PhilosophyRoute: PhilosophyRoute,
  PillarsRoute: PillarsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
